/**
 * data.js — All quiz questions and search index
 * Each day has exactly 3 quiz questions.
 */

const QUIZZES = {
  1: [
    { q: "Which command shows disk space usage in human-readable format?",
      options: ["ls -lh", "du -sh", "df -h", "pwd"], answer: 2 },
    { q: "What does chmod 600 do to a file?",
      options: ["Gives everyone read access", "Gives owner read/write only", "Makes file executable", "Removes all permissions"], answer: 1 },
    { q: "Which signal does 'kill -9' send to a process?",
      options: ["SIGTERM", "SIGHUP", "SIGKILL", "SIGINT"], answer: 2 },
  ],
  2: [
    { q: "What does 'set -e' do in a bash script?",
      options: ["Sets an environment variable", "Exits on any error", "Enables debug mode", "Encrypts the script"], answer: 1 },
    { q: "What is the correct cron syntax to run a job every 5 minutes?",
      options: ["5 * * * *", "*/5 * * * *", "0/5 * * * *", "* 5 * * *"], answer: 1 },
    { q: "What does $? return in bash?",
      options: ["Current process ID", "Exit code of last command", "Number of arguments", "Current directory"], answer: 1 },
  ],
  3: [
    { q: "What does 'git stash' do?",
      options: ["Permanently deletes uncommitted changes", "Saves uncommitted changes temporarily", "Creates a new branch", "Merges two branches"], answer: 1 },
    { q: "Which file should NEVER be committed to Git?",
      options: ["README.md", "package.json", ".env", "Dockerfile"], answer: 2 },
    { q: "What does 'git rebase -i HEAD~3' allow you to do?",
      options: ["Delete 3 commits permanently", "Interactively edit last 3 commits", "Merge 3 branches", "Reset to 3 commits ago"], answer: 1 },
  ],
  4: [
    { q: "What is the main benefit of multi-stage Docker builds?",
      options: ["Faster builds", "Smaller final image size", "Better security only", "Easier debugging"], answer: 1 },
    { q: "Which command runs a container in detached mode?",
      options: ["docker run -it", "docker run -d", "docker start -a", "docker exec -d"], answer: 1 },
    { q: "What does EXPOSE in a Dockerfile actually do?",
      options: ["Opens the port on the host", "Documents the intended port", "Blocks the port", "Maps to host port automatically"], answer: 1 },
  ],
  5: [
    { q: "What does 'depends_on' guarantee in Docker Compose?",
      options: ["The service is healthy before starting", "Start order only, not health", "Network connectivity", "Volume mounting order"], answer: 1 },
    { q: "Where should Docker Compose read secrets from?",
      options: ["Hardcoded in docker-compose.yml", "A .env file (not committed)", "Environment of the host directly", "A secrets.yaml file"], answer: 1 },
    { q: "Which command rebuilds images without using cache?",
      options: ["docker compose restart", "docker compose up --force", "docker compose build --no-cache", "docker compose pull"], answer: 2 },
  ],
  6: [
    { q: "Where are GitHub Actions workflow files stored?",
      options: [".github/actions/", "workflows/", ".github/workflows/", "actions/"], answer: 2 },
    { q: "Which syntax accesses a GitHub Secret called DB_PASS?",
      options: ["$DB_PASS", "${secrets.DB_PASS}", "${{ secrets.DB_PASS }}", "secrets[DB_PASS]"], answer: 2 },
    { q: "What does 'needs: test' do in a job definition?",
      options: ["Installs test dependencies", "Runs test job first", "Makes job depend on 'test' job completing", "Skips if tests fail"], answer: 2 },
  ],
  7: [
    { q: "What is the main advantage of blue-green deployment?",
      options: ["Cheaper infrastructure", "Zero-downtime deployments", "Faster build times", "Automatic scaling"], answer: 1 },
    { q: "Why should you avoid using only ':latest' tag in production?",
      options: ["It's slower to pull", "It's not pinned to a specific version", "It doesn't work with Kubernetes", "It costs more storage"], answer: 1 },
    { q: "What is a canary deployment?",
      options: ["Deploying to a random server", "Routing a small % of traffic to new version", "Only deploying at night", "A type of rollback strategy"], answer: 1 },
  ],
  8: [
    { q: "What AWS service provides virtual private networking?",
      options: ["VPN", "VPC", "VPS", "NAT"], answer: 1 },
    { q: "Which IAM principle should always be followed?",
      options: ["Root account for all tasks", "Grant maximum permissions upfront", "Least privilege", "Share credentials across teams"], answer: 2 },
    { q: "What does 'aws s3 sync' do differently than 'aws s3 cp'?",
      options: ["It's faster", "Only copies changed files, removes deleted", "Compresses files", "Works without credentials"], answer: 1 },
  ],
  9: [
    { q: "What does 'terraform plan' do?",
      options: ["Applies infrastructure changes", "Previews changes without applying", "Destroys infrastructure", "Initializes providers"], answer: 1 },
    { q: "Why store Terraform state in S3 with DynamoDB?",
      options: ["For faster deployments", "For team collaboration and state locking", "For cost savings", "For encryption only"], answer: 1 },
    { q: "What is a Terraform workspace used for?",
      options: ["Organizing code files", "Separating state per environment", "Running multiple providers", "Storing secrets"], answer: 1 },
  ],
  10: [
    { q: "What is the difference between a Pod and a Deployment?",
      options: ["No difference", "A Deployment manages Pods and handles rolling updates", "A Pod can scale automatically", "A Deployment is only for databases"], answer: 1 },
    { q: "What does a readiness probe control?",
      options: ["When a container restarts", "When traffic is sent to a pod", "Memory limits", "Storage allocation"], answer: 1 },
    { q: "What does 'kubectl apply -f' do?",
      options: ["Deletes resources in the file", "Creates or updates resources declaratively", "Runs a pod imperatively", "Scales a deployment"], answer: 1 },
  ],
};

const SEARCH_INDEX = [
  { day: "Day 1",  title: "File System Navigation",          id: "day1"  },
  { day: "Day 1",  title: "File Permissions & Ownership",     id: "day1"  },
  { day: "Day 1",  title: "Process Management",              id: "day1"  },
  { day: "Day 2",  title: "Variables, Conditionals & Loops", id: "day2"  },
  { day: "Day 2",  title: "Functions & Error Handling",      id: "day2"  },
  { day: "Day 2",  title: "Cron Jobs & Scheduling",          id: "day2"  },
  { day: "Day 3",  title: "Core Git Workflow",               id: "day3"  },
  { day: "Day 3",  title: "Branching & Merging",             id: "day3"  },
  { day: "Day 3",  title: ".gitignore & Secrets",            id: "day3"  },
  { day: "Day 4",  title: "Install Docker & Core Commands",  id: "day4"  },
  { day: "Day 4",  title: "Write a Production Dockerfile",   id: "day4"  },
  { day: "Day 4",  title: "Push to Docker Hub",              id: "day4"  },
  { day: "Day 5",  title: "Write a docker-compose.yml",      id: "day5"  },
  { day: "Day 5",  title: "Compose Commands",                id: "day5"  },
  { day: "Day 5",  title: "Environment Files & Overrides",   id: "day5"  },
  { day: "Day 6",  title: "Your First Workflow",             id: "day6"  },
  { day: "Day 6",  title: "Build & Push Docker Image",       id: "day6"  },
  { day: "Day 6",  title: "Secrets & Environment Variables", id: "day6"  },
  { day: "Day 7",  title: "SSH Deploy via GitHub Actions",   id: "day7"  },
  { day: "Day 7",  title: "Blue-Green Deployments",          id: "day7"  },
  { day: "Day 7",  title: "Rollbacks",                       id: "day7"  },
  { day: "Day 8",  title: "AWS CLI & IAM Setup",             id: "day8"  },
  { day: "Day 8",  title: "EC2 & S3 Essentials",             id: "day8"  },
  { day: "Day 8",  title: "VPC & Security Groups",           id: "day8"  },
  { day: "Day 9",  title: "Terraform Basics",                id: "day9"  },
  { day: "Day 9",  title: "Variables & Outputs",             id: "day9"  },
  { day: "Day 9",  title: "Remote State & Workspaces",       id: "day9"  },
  { day: "Day 10", title: "Core Concepts & kubectl",         id: "day10" },
  { day: "Day 10", title: "Deployment & Service YAML",       id: "day10" },
  { day: "Day 10", title: "ConfigMaps, Secrets & Probes",    id: "day10" },
];
